#!/bin/bash

export APPTAINER_CACHEDIR="/home/andreas/data/apptainer"
export NIM_CACHEDIR="$APPTAINER_CACHEDIR/nim"
export SIF_DIR="$APPTAINER_CACHEDIR/sif"

# NVIDIA API KEY
if [ -f .env ]; then
  export $(grep -v '^#' .env | xargs | envsubst)
fi

apptainer run \
    --nv \
    --bind $NIM_CACHEDIR:/opt/nim/.cache \
    --env NGC_API_KEY=$NGC_API_KEY \
    $SIF_DIR/llama-3.2-1b-instruct_1.8.sif